### ISSUE TITLE
请问下谷歌翻译怎么实现的啊

### ISSUE THREAD

**Issue by g0fcn** [aamirazad/tigertutoringtool#80]

**Comment by aamirazad** [comment]
The website has a google translate toggle on the home page. Make sure you don't have an adblocker on, and you should see a popup for which language to translate to. ![popup](https://github.com/aamirazad/tigertutoringtool/assets/82281117/0dc7a109-90d8-4e6f-a826-e38262dd8765)
This will translate the whole site. Do note though, this website was mainly made for my school and is organized for that, but the information is still useful!

**Comment by g0fcn** [comment]
I mean, I want to build my website with the same hugo theme that I used with you. Can you show me how to do that

**Comment by aamirazad** [comment]
Oh! Sure, I used [papermod](https://github.com/adityatelange/hugo-PaperMod). I would read the github wiki to learn how to configure it. If you need anything else, please ask!

**Comment by g0fcn** [comment]
好吧好吧好吧

**Comment by g0fcn** [comment]
请问具体操作教程呢

**Comment by aamirazad** [comment]
Sure.
1. Install hugo on whatever computer you have using this [guide](https://gohugo.io/installation/)
2. Create a new site `hugo new site MyNewWebsite --format yaml`
3. Add the papermod submodule 

```
git submodule add --depth=1 https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod
git submodule update --init --recursive # needed when you reclone your repo (submodules may not get cloned automatically)
```

(or can also clone the repo to the themes folder)
4. In the `config.yml` add `theme: ["PaperMod"]` (or whatever the folder name is)
5. Follow [this wiki](https://github.com/adityatelange/hugo-PaperMod/wiki/Installation) to configure it to how you like

**Comment by g0fcn** [comment]
emm

**Comment by g0fcn** [comment]
Language is really the biggest communication barrier

**Comment by g0fcn** [comment]
Thank you very much for your answer

**Comment by g0fcn** [comment]
I mean, I have a hugo website, I need to install this translation function, would like to ask you how to configure, thank you very much for your patient answer![29ab877c4bb4d24f.png](https://github.com/aamirazad/tigertutoringtool/assets/156695055/b6623977-8c53-45e2-8e69-3c200f0aefcb)

**Comment by aamirazad** [comment]
I see, I misunderstood. I actually use cloudflare apps with cloudflare pages (the service that deploys the website) adds that. But I think it's just a script that you need to add to the home page, like this? https://www.w3schools.com/howto/howto_google_translate.asp. This is the cloudflare app I'm using https://cloudflareapps.com/apps/google-translate but is gonna be going away :(

**Comment by g0fcn** [comment]
I see. Thank you so much

**Comment by aamirazad** [comment]
My pleasure!
